version: 0.0
os: linux
files:
 - source: /
   destination: /home/ec2-user/Vizdat-v2
hooks:
  AfterInstall:
   - location: scripts/install_app_dependencies
     timeout: 300
     runas: root
   - location: scripts/build
     timeout: 300
     runas: root
  ApplicationStart:
   - location: scripts/start_server
     timeout: 300
     runas: root
